project:
  type: book

book:
  title: "edav.info v2"
  author: "Joyce Robbins"
  date: today
  site-url: https://jtr13.github.io/edav2
  repo-url: https://github.com/jtr13/edav2
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - learning_R.qmd
    - factors.qmd
    - data_import.qmd
    - data_transformation.qmd
    - git_GitHub.qmd
    - learning_ggplot2.qmd
    - faceting.qmd
    - continuous_var.qmd
    - uni_categorical_var.qmd
    - two_continuous_var.qmd
    - multidimensional_continuous.qmd
    - multidimensional_categorical.qmd
    - missing_data.qmd
    - colors.qmd
    - time_series.qmd
    - spatial.qmd
    - cutting_room_floor.qmd 

format:
  html:
    theme: [default, style/edav3.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 60%
    
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source

