on:
  push:
    branches:
      - main
  schedule:
    # run every Saturday at 8am (12 UTC)
      - cron: '0 12 * * 6'

name: quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: setup R
        uses: r-lib/actions/setup-r@v2

      - name: setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Deploy 🚀
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages